### ISSUE TITLE
WMP v1.4 Release Checklist

### ISSUE THREAD

**Issue by zaerald** [waifu-motivator/waifu-motivator-plugin#268]
- [x] Update README
- [x] Update CHANGELOG
- [x] Update Welcome Dialog Message
- [x] Create GitHub release on master to publish to Marketplace
- [x] Upload new demo to Marketplace once published
